dist: bionic
sudo: required
language: sh

addons:
  apt:
    packages:
    - libxml2-utils

cache:
    directories:
     - .bazel_cache
     - ~/.bazel_binaries

_linux: &linux
  os: linux
_osx: &osx
  os: osx
  osx_image: xcode10.1

jobs:
  include:
# Test
    - <<: *linux
    - <<: *osx

before_install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      OS=darwin
    else
      OS=linux
    fi
    URL="https://github.com/bazelbuild/bazel/releases/download/2.0.0/bazel-2.0.0-installer-${OS}-x86_64.sh"
    wget -O install.sh "${URL}"
    chmod +x install.sh
    ./install.sh --user
    rm -f install.sh
  - cp .bazelrc-travis .bazelrc-local
script:
  - bash bazel test //...
  